version: '3'
services:
  config:
    container_name: config
    image: credifocus/microservices-config:1.0
    restart: always
    environment:
      URI: 'https://github.com/gasparbarancelli/microservices-2.git'
    ports:
      - 8888:8888
    expose:
      - "8888"